"use client";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/sidebar";
import SidebarWrapper from "./components/SidebarWrapper";
import { NextUIProvider } from "@nextui-org/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/* export const metadata: Metadata = {
  title: "Chat App",
  description: "Generated by create next app",
}; */

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-purple/10 h-screen`}
      >
        <NextUIProvider>
          <div className="grid grid-cols-9 gap-4 h-screen">
            <div className="h-full">
              <SidebarWrapper />
            </div>
            <div className="col-span-8 h-full">{children}</div>
          </div>
        </NextUIProvider>
      </body>
    </html>
  );
}
