import { image } from "@nextui-org/react";
import {
  ChatIcon,
  ContactIcon,
  People01,
  People02,
  People03,
  ProfileIcon,
} from "./image";

export const SidebarIconData = [
  {
    icon: ChatIcon,
    iconName: "Chat",
    iconWidth: 24,
    iconHeigh: 24,
    href: "/",
  },
  {
    icon: ContactIcon,
    iconName: "Contact",
    iconWidth: 24,
    iconHeigh: 24,
    href: "/contact",
  },
  {
    icon: ProfileIcon,
    iconName: "Profile",
    iconWidth: 24,
    iconHeigh: 24,
    href: "/profile",
  },
];

export const chatListData = [
  {
    id: 1,
    image: People01,
    name: "John Doe",
    message: "Hello, how are you?",
    time: "12:00",
    unread: 3,
    pin: true,
  },
  { id: 2,
    image: People02,
    name: "Jane Doe",
    message: "Hello, how are you?",
    time: "12:00",
    unread: 3,
    pin: false,
  },
  { id: 3,
    image: People03,
    name: "John Smith",
    message: "Hello, how are you?",
    time: "12:00",
    unread: 3,
    pin: true,
  },
  { id: 4,
    image: People01,
    name: "John Doe",
    message: "Hello, how are you?",
    time: "12:00",
    unread: 3,
    pin: false,
  },
  { id: 5,
    image: People02,
    name: "Jane Doe",
    message: "Hello, how are you?",
    time: "12:00",
    unread: 0,
    pin: true,
  },
  { id: 6,
    image: People03,
    name: "John Smith",
    message: "Hello, how are you?",
    time: "12:00",
    unread: 0,
    pin: false,
  },
  { id: 7,
    image: People03,
    name: "John Smith Group",
    message: "Hello, how are you?",
    time: "12:00",
    unread: 0,
    pin: true,
    type: "group"
  },
  { id: 8,
    image: People01,
    name: "John Doe",
    message: "Hello, how are you?",
    time: "12:00",
    unread: 3,
    pin: false,
  },
  { id: 9,
    image: People02,
    name: "Jane Doe Group",
    message: "Hello, how are you?",
    time: "12:00",
    unread: 3,
    pin: true,
    type: "group"
  },
  { id: 10,
    image: People01,
    name: "John Doe Group",
    message: "Hello, how are you?",
    time: "12:00",
    unread: 0,
    pin: false,
    type: "group"
  },
  { id: 11,
    image: People03,
    name: "John Do3",
    message: "Hello, how are you?",
    time: "12:00",
    unread: 3,
    pin: false,
  },
];

export const chatHistoryData = [
  {
    participants: [
      { userId: 1, username: "John Doe", image: People01 },
      { userId: "admin", username: "Admin" },
    ],
    messages: [
      { messageId: "msg1", senderId: "admin", timestamp: "10:00", type: "text", content: "Hey! How's it going?" },
      { messageId: "msg2", senderId: 1, timestamp: "10:02", type: "text", content: "Hi Admin! I'm good, just working on a project. You?" },
    ],
  },
];

export const profileData = {
  id: 1,
  name: "John Doe",
  phone: "123456789",
  image: People01,
  work: "Software Engineer",
  birthday: "01/01/1990",
  location: "New York, USA",
};

